package routers

import (
	"github.com/gin-gonic/gin"
	_ "github.com/mzit/order_api/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/mzit/order_api/pkg/setting"
	v1 "github.com/mzit/order_api/routers/api/v1"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func InitRouter() *gin.Engine {
	r := gin.New()
	r.Use(gin.Logger())
	r.Use(gin.Recovery())
	gin.SetMode(setting.ServerSetting.RunMode)

	apiv1 := r.Group("/api/v1")

	{
		//
		apiv1.GET("/order", v1.GetOrder)
		apiv1.GET("/orders", v1.GetOrders)
		apiv1.GET("/order_items/:order_sn", v1.GetOrderItems)

	}
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	return r
}
